# Generated by Django 5.1.6 on 2025-02-14 19:12

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='certificate',
            field=models.FileField(upload_to='assistants/certificates/'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='certificate',
            field=models.FileField(upload_to='doctors/certificates/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField(default=django.utils.timezone.localdate)),
                ('app_time', models.TimeField(default=datetime.time(19, 11, 57, 589032))),
                ('app_aprv', models.BooleanField(default=False)),
                ('app_done', models.BooleanField(default=False)),
                ('app_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctor')),
                ('app_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.CharField(default='', max_length=250)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('marital', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('blood', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('O+', 'O+')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('report_screenshot', models.ImageField(null=True, upload_to='reports/screenshots/')),
                ('report_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.assistant')),
                ('report_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.doctor')),
                ('report_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.patient')),
            ],
        ),
    ]
