# Generated by Django 5.1.6 on 2025-02-15 09:42

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_assistant_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_time',
            field=models.TimeField(default=datetime.time(9, 42, 37, 109153)),
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('diagnostic_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostic_name', models.CharField(default='', max_length=250)),
                ('diag_date', models.DateField(default=django.utils.timezone.now)),
                ('diag_time', models.TimeField(default=datetime.datetime(2025, 2, 15, 10, 42, 37, 147611))),
                ('diagnostic_screenshot', models.ImageField(null=True, upload_to='diagnostics/screenshots/')),
                ('diag_type', models.CharField(choices=[('Alzheimer', 'Alzheimer'), ('Covid', 'Covid'), ('Tubes', 'Tubes')], max_length=100)),
                ('diagnostic_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='users.assistant')),
                ('diagnostic_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='users.doctor')),
                ('diagnostic_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='users.patient')),
            ],
        ),
    ]
