# Generated by Django 5.1.6 on 2025-02-15 09:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_appointment_app_time_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='diag_time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 15, 10, 50, 23, 868753)),
        ),
    ]
