# Generated by Django 5.1.6 on 2025-02-15 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_appointment_app_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='diag_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
