# Generated by Django 5.1.6 on 2025-02-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_diagnostic_diag_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='diag_type',
            field=models.CharField(choices=[('Alzheimer', 'Alzheimer'), ('Covid', 'Covid'), ('Tubes', 'Tubes'), ('Dementia', 'Dementia'), ('Epilepsy', 'Epilepsy'), ('Hepatitis', 'Hepatitis'), ('Hypertension', 'Hypertension'), ('Kidney disease', 'Kidney disease')], max_length=100),
        ),
    ]
