# Generated by Django 5.1.6 on 2025-02-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_diagnostic_diag_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='usertype',
        ),
    ]
