# Generated by Django 5.1.6 on 2025-03-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='usertype',
            new_name='role',
        ),
    ]
