# Generated by Django 5.1.6 on 2025-03-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_experience_customuser_hospital_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='specialization',
        ),
    ]
