# Generated by Django 5.1.6 on 2025-04-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctors/certificates/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
