# Generated by Django 5.1.6 on 2025-04-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_doctor_certificate_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='assistants/certificates/'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
